version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "4002:4002"
    environment:
      DATABASE_URL: "postgresql://postgres:mysecretpassword@postgres:5432/postgres?schema=user"
    depends_on:
      - postgres

  appointment-service:
    build:
      context: ./appointement-service
    ports:
      - "4001:4001"
    environment:
      USER_SERVICE_URL: "http://user-service:4002"
      DATABASE_URL: "postgresql://postgres:mysecretpassword@postgres:5432/postgres?schema=appointment"
    depends_on:
      - postgres

  frontend-service:
    build:
      context: ./frontend-service
    ports:
      - "4003:4003" # Serve via Nginx on port 80 internally
    depends_on:
      - user-service
      - appointment-service    

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
