version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "4002:4002"
    environment:
      DATABASE_URL: "postgresql://postgres:mysecretpassword@postgres:5432/postgres?schema=user"
    depends_on:
      - postgres

  appointment-service:
    build:
      context: ./appointement-service
    ports:
      - "4001:4001"
    environment:
      DATABASE_URL: "postgresql://postgres:mysecretpassword@postgres:5432/postgres?schema=appointment"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
